### ISSUE TITLE
is the "if (cid0 == 0x01 && cid1 == 0x02 && cid2 == 0x03 && cid3 == 0x04)" really correct?

### ISSUE THREAD

**Issue by chk2902** [libjpeg-turbo/ijg#2]
The image

[image](https://user-images.githubusercontent.com/47900237/226316342-c71da149-ba1f-4fa8-b00c-5dbedacfb0bf.jpg)

is converted to RGB using wrong colors, because it is detected as being 

`cinfo->jpeg_color_space = JCS_YCCK`

but in reality it should be JCS_CMYK (the viewers I checked do display it with a white background).

The comment for the if() clause was

```
    /* For robust detection of standard colorspaces
     * regardless of the presence of special markers,
     * check component IDs from SOF marker first.
     */
    if      (cid0 == 0x01 && cid1 == 0x02 && cid2 == 0x03 && cid3 == 0x04)
      cinfo->jpeg_color_space = JCS_YCCK;
```

But this fails in case of the attached file.

**Comment by dcommander** [comment]
The libjpeg-turbo/ijg repository is a reference for the libjpeg code base.  If this issue exists in the libjpeg-turbo code base, then it needs to be filed under libjpeg-turbo/libjpeg-turbo.
